# yaml-language-server: $schema=https://raw.githubusercontent.com/flipt-io/flipt/main/config/flipt.schema.json

# version: "1.0"
log:
  level: DEBUG

# authentication:
#   required: false

# ui:
#   enabled: true

authentication:
  required: true
  session:
    domain: "localhost:8080"
    secure: false
  methods:
    token:
      enabled: true
      bootstrap:
        token: "secret"
        expiration: 24h
      cleanup:
        interval: 2h
        grace_period: 48h

cors:
  enabled: true
  allowed_origins: ["*"]
# cache:
#   enabled: false
#   backend: memory
#   ttl: 60s
#   redis:
#     host: localhost
#     port: 6379
#   memory:
#     eviction_interval: 5m # evict expired items every 5m

# server:
#   protocol: http
#   host: 0.0.0.0
#   https_port: 443
#   http_port: 8080
#   grpc_port: 9000
